  version: "3.3"
  services:
    mysql:
      container_name: "python-db"
      image: "mysql:8"
      volumes:
        - ./mysql:/docker-entrypoint-initdb.d
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_USER: python
        MYSQL_PASSWORD: python
        MYSQL_DATABASE: or_db
        
    python:
      container_name: "python"
      build: ./app/
      ports:
        - "5000:5000"
