version: "3"
services:
  mysql:
    container_name: "python-db"
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: python
      MYSQL_PASSWORD: python
      MYSQL_DATABASE: or_db
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d

  app:
    build: ./docker/
    ports:
      - "5000:5000"
    depends_on:
     - mysql
 

