name: Docker Image Python Hello World

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Build Docker compose
      run: |
        docker-compose up -d
      #run: docker build . --file app/Dockerfile --tag oralush49/or_repo:python-hello-world
    - name: login to docker hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    # - name: Docker Push
    #  run: docker push oralush49/or_repo:python-hello-world
    #- name: Docker run
    #  run: docker run -p 5000:5000 oralush49/or_repo:python-hello-world
